# Generated by Django 5.1.4 on 2025-11-19 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Season Title')),
                ('year', models.CharField(max_length=9, verbose_name='Season Year')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Registration Amount')),
                ('accept_response', models.BooleanField(default=False, verbose_name='Accept Response')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin User')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reg_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Register ID')),
                ('player_name', models.CharField(max_length=100, verbose_name='Player Name')),
                ('father_name', models.CharField(max_length=100, verbose_name='Father’s Name')),
                ('category', models.CharField(choices=[('Under 21', 'Under 21'), ('21 and Above', '21 and Above')], max_length=25, verbose_name='Category')),
                ('age', models.PositiveIntegerField(verbose_name='Player Age')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender')),
                ('tshirt_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=4, verbose_name='T-Shirt Size')),
                ('occupation', models.CharField(choices=[('student', 'Student'), ('self-employed', 'Self Employed'), ('business', 'Business'), ('other', 'Others')], default=3, max_length=14, verbose_name='Player Occupation')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('wathsapp_number', models.CharField(max_length=10, verbose_name='Wathsapp Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('adhar_card', models.CharField(max_length=12, unique=True, verbose_name='Aadhar Card Number')),
                ('player_image', models.ImageField(upload_to='player_images/', verbose_name='Player Image')),
                ('district', models.CharField(choices=[('Kanyakumari', 'Kanyakumari'), ('Tirunelveli', 'Tirunelveli'), ('Thoothukudi', 'Thoothukudi'), ('Tenkasi', 'Tenkasi'), ('Virudhunagar', 'Virudhunagar'), ('Ramanathapuram', 'Ramanathapuram'), ('Theni', 'Theni'), ('Madurai', 'Madurai'), ('Sivagangai', 'Sivagangai'), ('Dindigul', 'Dindigul'), ('Pudukkottai', 'Pudukkottai'), ('Thanjavur', 'Thanjavur'), ('Thiruvarur', 'Thiruvarur'), ('Nagapattinam', 'Nagapattinam'), ('Tiruchi', 'Tiruchi'), ('Ariyalur', 'Ariyalur'), ('Mayiladuthurai', 'Mayiladuthurai'), ('Perambalur', 'Perambalur'), ('Cuddalore', 'Cuddalore'), ('Pondicherry', 'Pondicherry'), ('Karaikkal', 'Karaikkal'), ('Chennai', 'Chennai'), ('Tiruvallur', 'Tiruvallur'), ('Kanchipuram', 'Kanchipuram'), ('Chengalpattu', 'Chengalpattu'), ('Tiruvannamalai', 'Tiruvannamalai'), ('Tirupattur', 'Tirupattur'), ('Vellore', 'Vellore'), ('Ranipet', 'Ranipet'), ('Kallakkurichi', 'Kallakkurichi'), ('Villuppuram', 'Villuppuram'), ('Krishnagiri', 'Krishnagiri'), ('Dharmapuri', 'Dharmapuri'), ('Nilgiris', 'Nilgiris'), ('Erode', 'Erode'), ('Salem', 'Salem'), ('Coimbatore', 'Coimbatore'), ('Tiruppur', 'Tiruppur'), ('Namakkal', 'Namakkal'), ('Karur', 'Karur')], max_length=100, verbose_name='District')),
                ('zone', models.CharField(default='ZONE A', editable=False, max_length=10, verbose_name='Zone')),
                ('pin_code', models.PositiveIntegerField(verbose_name='PIN Code')),
                ('address', models.TextField(verbose_name='Address')),
                ('first_preference', models.CharField(choices=[('batting', 'Batting'), ('bowling', 'Bowling')], default=0, max_length=10, verbose_name='First Preference')),
                ('batting_arm', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default=0, max_length=10, verbose_name='Batting Arm')),
                ('role', models.CharField(choices=[('BATTING', 'BATTING'), ('BOWLLING', 'BOWLLING'), ('ALL-ROUNDER', 'ALL-ROUNDER')], default=0, max_length=100, verbose_name='Player Role')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Player Paid')),
                ('tx_id', models.CharField(blank=True, max_length=255, verbose_name='Transition ID#')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Is the player got Selected')),
                ('points', models.IntegerField(default=-99, verbose_name='Player Points on Trails')),
                ('is_compleated', models.BooleanField(default=False, verbose_name='Is Registration Compleated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season', verbose_name='Season Configuration')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_registration', models.BooleanField(default=True, verbose_name='Enable Player Registration')),
                ('show_points_table', models.BooleanField(default=True, verbose_name='Show Points Table to Public')),
                ('enable_results', models.BooleanField(default=False, verbose_name='Enable Player Results Viewing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin User')),
                ('current_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.season', verbose_name='Current Season')),
            ],
        ),
    ]
