# Generated by Django 5.1.4 on 2025-11-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_generalsettings_options_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='razorpay_key_id',
            field=models.CharField(default='', max_length=255, verbose_name='Razorpay Key ID'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='razorpay_key_secret',
            field=models.CharField(default='', max_length=255, verbose_name='Razorpay Key Secret'),
        ),
    ]
