# Generated by Django 5.1.4 on 2025-11-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_generalsettings_razorpay_key_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
