# Generated by Django 5.1.4 on 2025-11-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='registration_form_editable',
            field=models.BooleanField(default=True, verbose_name='Is Registration Form Editable'),
        ),
    ]
