# Generated by Django 5.1.4 on 2025-11-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_season_registration_form_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_compleated',
            field=models.BooleanField(default=False, verbose_name='Is Payment Completed'),
        ),
    ]
