# Generated by Django 5.1.4 on 2025-11-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment_is_compleated'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='callback_url',
            field=models.URLField(default='', max_length=500, verbose_name='Payment Callback URL'),
        ),
    ]
