# Generated by Django 5.1.4 on 2025-11-21 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_generalsettings_callback_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerregistration',
            name='adhar_card',
            field=models.CharField(max_length=12, verbose_name='Adhar Card'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='reg_id',
            field=models.CharField(editable=False, max_length=20, verbose_name='Register ID'),
        ),
        migrations.AddConstraint(
            model_name='playerregistration',
            constraint=models.UniqueConstraint(fields=('season', 'reg_id'), name='unique_reg_id_per_season'),
        ),
        migrations.AddConstraint(
            model_name='playerregistration',
            constraint=models.UniqueConstraint(fields=('season', 'adhar_card'), name='unique_adhar_per_season'),
        ),
    ]
