# Generated by Django 5.1.4 on 2025-11-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_playerregistration_adhar_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerregistration',
            name='is_mail_sent',
            field=models.BooleanField(default=False, verbose_name='Is the Mail was Sent'),
        ),
    ]
